// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebgazkffxslodxhyuahb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZ2F6a2ZmeHNsb2R4aHl1YWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxMDk1MzMsImV4cCI6MjA4MjY4NTUzM30.BSELyub563EK_p1xnAQ182_W4nknDzC9Pv29aUppVKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});